# Generated by Django 4.1.1 on 2022-10-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=80)),
                ('inicio', models.CharField(max_length=80)),
                ('data_hora', models.DateTimeField()),
                ('motorista', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=1)),
                ('vagas', models.IntegerField()),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('genero', models.CharField(max_length=1)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
