# Generated by Django 4.1.1 on 2022-10-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carona",
            name="data_hora",
            field=models.DateTimeField(verbose_name="data/hora"),
        ),
        migrations.AlterField(
            model_name="carona",
            name="destino",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="carona",
            name="inicio",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="carona",
            name="motorista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="office.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="carona",
            name="preco",
            field=models.FloatField(default=0.0, verbose_name="preço"),
        ),
        migrations.AlterField(
            model_name="carona",
            name="vagas",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="endereco",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
