# Generated by Django 4.1.1 on 2022-10-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0002_alter_carona_data_hora_alter_carona_destino_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carona",
            name="max_pontos",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="carona",
            name="min_pontos",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="carona",
            name="pontuacao",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usuario",
            name="max_pontos",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="usuario",
            name="min_pontos",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="usuario",
            name="pontuacao",
            field=models.FloatField(default=0.0),
        ),
    ]
