# Generated by Django 4.1.1 on 2022-11-03 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "office",
            "0003_carona_max_pontos_carona_min_pontos_carona_pontuacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="carona",
            name="passageiros",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)s_passageiros", to="office.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="carona",
            name="motorista",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_motorista",
                to="office.usuario",
            ),
        ),
    ]
