# Generated by Django 4.1.1 on 2022-11-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0004_carona_passageiros_alter_carona_motorista"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carona",
            name="genero",
        ),
    ]
