# Generated by Django 4.1.1 on 2022-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0005_remove_carona_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carona",
            name="passageiros",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_passageiros",
                to="office.usuario",
            ),
        ),
    ]
