# Generated by Django 4.1.1 on 2022-11-29 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0007_usuario_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carona",
            name="passageiros",
        ),
        migrations.AddField(
            model_name="usuario",
            name="carona",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="office.carona",
            ),
        ),
    ]
