# Generated by Django 4.1.1 on 2022-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0009_alter_usuario_carona"),
    ]

    operations = [
        migrations.AddField(
            model_name="carona",
            name="chegada",
            field=models.DateTimeField(blank=True, null=True, verbose_name="chegada"),
        ),
        migrations.AddField(
            model_name="carona",
            name="partida",
            field=models.DateTimeField(blank=True, null=True, verbose_name="partida"),
        ),
    ]
